import { ICrashEventModel } from "./ICrashEventModel";
import { INonMotoristCrashModel } from "./INonMotoristCrashModel";
import { INonMotoristImpairModel } from "./INonMotoristImpairModel";
import { INonMotoristPriorModel } from "./INonMotoristPriorModel";
import { INonMotoristSafetyEquipmentModel } from "./INonMotoristSafetyEquipmentModel";
import { IParkWorkVehicleModel } from "./IParkWorkVehicleModel";
import { IPedestrianBicycleModel } from "./IPedestrianBicycleModel";
import { IPersonModel } from "./IPersonModel";
import { IPointModel } from "./IPointModel";
import { IVehicleCrashModel } from "./IVehicleCrashModel";
import { IVehicleDetailModel } from "./IVehicleDetailModel";
import { IVehicleEventModel } from "./IVehicleEventModel";

export interface IAccidentModel {
  consecutiveNumber?: number;
  stateNumber?: number;
  stateName?: string;
  numberOfVehicleFormsSubmittedAll?: number;
  numberOfMotorVehiclesInTransportMvit?: number;
  numberOfParkedWorkingVehicles?: number;
  numberOfFormsSubmittedForPersonsNotInMotorVehicles?: number;
  numberOfPersonsNotInMotorVehiclesInTransportMvit?: number;
  numberOfPersonsInMotorVehiclesInTransportMvit?: number;
  numberOfFormsSubmittedForPersonsInMotorVehicles?: number;
  county?: number;
  city?: number;
  dayOfCrash?: number;
  monthOfCrash?: number;
  yearOfCrash?: number;
  dayOfWeek?: number;
  hourOfCrash?: number;
  minuteOfCrash?: number;
  nationalHighwaySystem?: number;
  landUse?: number;
  landUseName?: string;
  functionalSystem?: number;
  functionalSystemName?: string;
  ownership?: number;
  ownershipName?: string;
  routeSigning?: number;
  routeSigningName?: string;
  trafficwayIdentifier?: string;
  trafficwayIdentifier2?: string;
  milepoint?: number;
  location?: IPointModel;
  specialJurisdiction?: number;
  specialJurisdictionName?: string;
  firstHarmfulEvent?: number;
  firstHarmfulEventName?: string;
  mannerOfCollision?: number;
  mannerOfCollisionName?: string;
  relationToJunctionWithinInterchangeArea?: string;
  relationToJunctionSpecificLocation?: number;
  relationToJunctionSpecificLocationName?: string;
  typeOfIntersection?: string;
  workZone?: string;
  relationToTrafficway?: number;
  relationToTrafficwayName?: string;
  lightCondition?: number;
  lightConditionName?: string;
  atmosphericConditions1?: number;
  atmosphericConditions1Name?: string;
  atmosphericConditions2?: number;
  atmosphericConditions2Name?: string;
  atmosphericConditions?: number;
  atmosphericConditionsName?: string;
  schoolBusRelated?: string;
  railGradeCrossingIdentifier?: string;
  hourOfNotification?: number;
  minuteOfNotification?: number;
  hourOfArrivalAtScene?: number;
  minuteOfArrivalAtScene?: number;
  hourOfEmsArrivalAtHospital?: number;
  minuteOfEmsArrivalAtHospital?: number;
  relatedFactorsCrashLevel1?: number;
  relatedFactorsCrashLevel1Name?: string;
  relatedFactorsCrashLevel2?: number;
  relatedFactorsCrashLevel2Name?: string;
  relatedFactorsCrashLevel3?: number;
  relatedFactorsCrashLevel3Name?: string;
  numberOfFatalities?: number;
  numberOfDrunkDrivers?: number;
  timestampOfCrash?: Date;

  crashEvents: ICrashEventModel[];
  nonMotoristsCrash: INonMotoristCrashModel[];
  nonMotoristsImpair: INonMotoristImpairModel[];
  nonMotoristsPrior: INonMotoristPriorModel[];
  nonMotoristsSafetyEquipment: INonMotoristSafetyEquipmentModel[];
  parkWorkVehicles: IParkWorkVehicleModel[];
  pedestrianBicycles: IPedestrianBicycleModel[];
  persons: IPersonModel[];
  vehicleCrashs: IVehicleCrashModel[];
  vehicleDetails: IVehicleDetailModel[];
  vehicleEvents: IVehicleEventModel[];
}
